---
# Play to configure Ansible Automation Platform (AAP) common resources
- name: Configure AAP resources
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "common/vars.yml"

  pre_tasks:
    - name: Load inventories
      ansible.builtin.include_vars:
        file: "common/inventory.yml"
        name: inventory_vars

    - name: Load hosts
      ansible.builtin.include_vars:
        file: "common/hosts.yml"
        name: host_vars

    - name: Load projects
      ansible.builtin.include_vars:
        file: "common/projects.yml"
        name: project_vars

    - name: Load job templates
      ansible.builtin.include_vars:
        file: "common/job_templates.yml"
        name: job_template_vars

    # - name: Load workflow templates
    #   ansible.builtin.include_vars:
    #     file: "environments/{{ target_env }}/workflow_templates.yml"
    #     name: workflow_vars

  roles:
    # Create inventories
    - role: infra.aap_configuration.controller_inventories
      when: inventory_vars.controller_inventories is defined
      vars:
        controller_inventories: "{{ inventory_vars.controller_inventories }}"

    # Create hosts
    - role: infra.aap_configuration.controller_hosts
      when: host_vars.controller_hosts is defined
      vars:
        controller_hosts: "{{ host_vars.controller_hosts }}"

    # Create projects
    - role: infra.aap_configuration.controller_projects
      when: project_vars.controller_projects is defined
      vars:
        controller_projects: "{{ project_vars.controller_projects }}"

    # Create job templates
    - role: infra.aap_configuration.controller_job_templates
      when: job_template_vars.controller_templates is defined
      vars:
        controller_templates: "{{ job_template_vars.controller_templates }}"

#     # # Create workflow templates
#     # - role: infra.aap_configuration.workflow_template
#     #   when: workflow_vars.controller_workflows is defined
#     #   vars:
#     #     controller_workflows: "{{ workflow_vars.controller_workflows }}"

# Play to manage inventories and hosts for each environment
# - name: Manage Inventories and Hosts for Environments
#   hosts: localhost
#   connection: local
#   gather_facts: false
#   vars_files:
#     - "common/vars.yml"

#   tasks:
#     - name: Get the list of environments
#       block:
#         - name: Find environment directories
#           ansible.builtin.find:
#             paths: "./environments"
#             file_type: directory
#             depth: 1
#           register: found_dirs

#         - name: Extract environment names
#           ansible.builtin.set_fact:
#             vsphere_env_list: "{{ found_dirs.files | map(attribute='path') | map('basename') | list }}"

#         - name: Show the result
#           ansible.builtin.debug:
#             var: vsphere_env_list

#     - name: Manage inventories and hosts for each environment
#       when: vsphere_env_list is defined and vsphere_env_list | length > 0
#       ansible.builtin.include_tasks:
#         file: "inventory.yml"
#       vars:
#         target_env: "{{ item }}"
#       loop: "{{ vsphere_env_list }}"
