---
# Play to configure Ansible Automation Platform (AAP) common resources
- name: Configure AAP resources
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "controller/vars.yml"

  pre_tasks:
    - name: Load inventories
      ansible.builtin.include_vars:
        file: "controller/inventory.yml"
        name: inventory_vars

    - name: Load hosts
      ansible.builtin.include_vars:
        file: "controller/hosts.yml"
        name: host_vars

    - name: Load projects
      ansible.builtin.include_vars:
        file: "controller/projects.yml"
        name: project_vars

    - name: Load job templates
      ansible.builtin.include_vars:
        file: "controller/job_templates.yml"
        name: job_template_vars

  roles:
    # Create inventories
    - role: infra.aap_configuration.controller_inventories
      when: inventory_vars.controller_inventories is defined
      vars:
        controller_inventories: "{{ inventory_vars.controller_inventories }}"

    # Create hosts
    - role: infra.aap_configuration.controller_hosts
      when: host_vars.controller_hosts is defined
      vars:
        controller_hosts: "{{ host_vars.controller_hosts }}"

    # Create projects
    - role: infra.aap_configuration.controller_projects
      when: project_vars.controller_projects is defined
      vars:
        controller_projects: "{{ project_vars.controller_projects }}"

    # Create job templates
    - role: infra.aap_configuration.controller_job_templates
      when: job_template_vars.controller_templates is defined
      vars:
        controller_templates: "{{ job_template_vars.controller_templates }}"
