---
controller_hosts:
  - name: localhost
    description: "Localhost for management tasks"
    enabled: true
    state: present
    inventory: "{{ inventory_name }}"
    variables:
      ansible_connection: local
      ansible_become: false
      ansible_python_interpreter: auto_silent
