---
name: Release

run-name: >
  ${{ github.workflow }} - Event: ${{ github.event_name }}, branch: ${{ github.head_ref || github.ref_name }}

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup job
        run: echo "Setting up job environment"

  release:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Ansible collections
        run: |
          ansible-galaxy collection install -r requirements.yml

      - name: Run AAP configuration playbook
        env:
          AAP_TOKEN: ${{ secrets.AAP_TOKEN }}
        run: |
          ansible-playbook main.yml | tee ansible_playbook.log

      - name: Add ansible-playbook output to summary
        run: |
          echo '### Ansible Playbook Output' >> $GITHUB_STEP_SUMMARY
          cat ansible_playbook.log >> $GITHUB_STEP_SUMMARY
