---
controller_hosts:
  - name: localhost
    description: "Management vCenter for Dev"
    enabled: true
    state: present
    inventory: "{{ mgmt_inventory }}"
    variables:
      ansible_connection: local
      ansible_become: false
      ansible_python_interpreter: auto_silent
      vcenter_hostname: mgmt-vcenter.dev.rlabs.com
      vcenter_username: administrator@vsphere.local
  - name: localhost
    description: "Workload vCenter for Dev"
    enabled: true
    state: present
    inventory: "{{ wkld_inventory }}"
    variables:
      ansible_connection: local
      ansible_become: false
      ansible_python_interpreter: auto_silent
      vcenter_hostname: wkld-vcenter.dev.rlabs.com
      vcenter_username: administrator@vsphere.local
